[project]
name = "mextractor"
version = "6.0.2"
description = "mextractor can extract media metadata to YAML and read them"
readme = "README.md"
authors = [{name = "Can H. Tartanoglu", email = "canhtart@gmail.com"}]
license = "MIT OR Apache-2.0"
keywords = ["metadata", "video", "image", "bigdata"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

requires-python = ">=3.10,<3.14"
dependencies = [
    "typer<1",
    "ruamel.yaml",
    "numpy",
    "pydantic>=2.0,<3",
    "pydantic-numpy>=7.0.0",
    "opencv-python-headless>=4.6.0,<5",
]

[project.urls]
Repository = "https://github.com/caniko/media-metadata-extractor"
Homepage = "https://pypi.org/project/mextractor/"

[project.scripts]
mextractor = "mextractor.cli:cli_app"

[project.optional-dependencies]
video-extract = ["ffmpeg-python"]
video = ["ffmpeg-python"]

[dependency-groups]
dev = ["pytest>=7.1.2,<8", {include-group = "format"}, {include-group = "type_checking"}, "ffmpeg-python"]
format = ["black", "isort", "ruff"]
type_checking = ["pyright"]

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120

[tool.pyright]
include = ["mextractor/**", "tests/**"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
